#define TAT_STAT_MAXIMUM 13
#define TAT_STAT_USEFULL_MINIMUM 8
#define TAT_BASIC_STAT_POINTS 4

#define TAT_AVAILABLE_STATS_LIST \
	STATKEY_STR = TAT_STAT_ENTRY("Strength", 2, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_PER = TAT_STAT_ENTRY("Perception", 1, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_INT = TAT_STAT_ENTRY("Intelligence", 1, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_CON = TAT_STAT_ENTRY("Constitution", 1, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_WIL = TAT_STAT_ENTRY("Willpower", 1, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_SPD = TAT_STAT_ENTRY("Speed", 2, 10, TAT_STAT_USEFULL_MINIMUM, TAT_STAT_MAXIMUM), \
	STATKEY_LCK = TAT_STAT_ENTRY("Fortune", 0.5, 10, TAT_STAT_USEFULL_MINIMUM, 16)

#define TAT_STATS_ORDER_LIST list( \
	STATKEY_STR, \
	STATKEY_PER, \
	STATKEY_INT, \
	STATKEY_CON, \
	STATKEY_WIL, \
	STATKEY_SPD, \
	STATKEY_LCK \
)
